services:
  - type: web
    name: zen-zone
    env: node
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_TOKEN
        generateValue: true
